
server:
  port: 8081

logging:
  level:
    hu.flowacademy.bands: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bands
    username: root
    password: P4ssword+
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create